version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=proxy
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/caddy_data:/data
    restart: unless-stopped

networks:
  public:
    external: true

volumes:
  caddy_data: {}