version: "3"
services:
  telegram_file_handler:
    build: .
    image: davidadrianrg/telegram_file_handler:v1.1
    container_name: telegram_file_handler
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WATCH_FOLDER=${WATCH_FOLDER}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
      - DOWNLOADS_FOLDER=${DOWNLOADS_FOLDER}
      - FILMS_FOLDER=${FILMS_FOLDER}
      - SERIES_FOLDER=${SERIES_FOLDER}
      - IMDB_TOKEN=${IMDB_TOKEN}
    volumes:
      - /media/ssd/peliculas:/home/bot/app/peliculas
      - /media/ssd/series:/home/bot/app/series
      - /media/ssd/descargas:/home/bot/app/descargas
      - /media/ssd/torrents:/home/bot/app/torrents
    restart: unless-stopped