version: "3"
services:
  telegram_file_handler:
    build: .
    image: davidadrianrg/telegram_file_handler:v1.0
    container_name: telegram_file_handler
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WATCH_FOLDER=${WATCH_FOLDER}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
    volumes:
      - /media/ssd/peliculas:/peliculas
      - /media/ssd/series:/series
      - /media/ssd/descargas:/descargas
      - /media/ssd/torrents:/torrents
    restart: unless-stopped