version: '3'

services:
  filebrowser:
    networks:
      - public
    labels:
      - caddy="${FQDN_EXTERNAL}"
      - caddy.reverse_proxy="{{upstreams 80}}"

networks:
  public:
    external: true
