version: "3.7"
services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    restart: unless-stopped
    init: true
    depends_on:
      - db
    networks:
      - public
      - private
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: miniflux_db
    restart: unless-stopped
    init: true
    env_file:
      - .env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - private
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  private:
    external: true
  public:
    external: true