version: "3.7"
services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    init: true
    depends_on:
      - db
    networks:
      - proxy
      - internal
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: miniflux_db
    init: true
    env_file:
      - .env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  internal:
  proxy:
    external: true