version: '3'
services:
    croc:
       image: schollz/croc:master
       container_name: croc
       environment:
            - CROC_PASS=${CROC_PASSWORD}
            - TZ=Europe/Madrid
       ports:
            - 9009:9009
       restart: unless-stopped