version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    #labels:
      #com.centurylinklabs.watchtower.monitor-only: "true" #To monitor with watchtower
    volumes:
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
        - /dev/ttyACM0 #To add zigbee gateway
    environment:
      - TZ=Europe/Madrid
    healthcheck:
      test: 'curl -m 90 -sLf http://127.0.0.1:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    restart: unless-stopped
