version: '3'
services:
  homeassistant:
    networks:
      - public
    labels:
      - caddy="${FQDN}"
      - caddy.reverse_proxy="{{upstreams 8123}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true