version: '3'

services:
  radarr:
    networks:
      - public
    labels:
      - caddy="${FQDN}"
      - caddy.tls="internal"
      - caddy.reverse_proxy="{{upstreams 7878}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true