version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
    # By default update all containers automatically
      - WATCHTOWER_LABEL_ENABLE=false # Set to true for update only labeled containers (com.centurylinklabs.watchtower.enable=true)
      - WATCHTOWER_MONITOR_ONLY=false # Set to true for monitor without update and optinally label containers with (com.centurylinklabs.watchtower.monitor-only=true)
      - WATCHTOWER_SCHEDULE="0 0 4 * * *"
      #- WATCHTOWER_NOTIFICATIONS=gotify
      #- WATCHTOWER_NOTIFICATION_GOTIFY_URL="https://my.gotify.tld/"
      #- WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN="SuperSecretToken"
    networks:
      - private

networks:
  private:
    external: true