version: '3'
services:
  filebrowser:
   image: filebrowser/filebrowser:pi
   container_name: filebrowser
   restart: unless-stopped
   volumes:
    - /media/ssd:/srv
    - ./data/filebrowser.db:/database.db
   environment:
    - FB_USERNAME=${FB_USERNAME}
    - FB_PASSWORD=${FB_PASSWORD}
  webdav:
   container_name: webdav
   image: ugeek/webdav:arm
   restart: unless-stopped
   volumes:
    - /media/ssd:/media
   environment:
    - USERNAME=${USER_WEBDAV}
    - PASSWORD=${PASSWORD_WEBDAV}
    - UID=1000
    - GID=1000
    - TZ=Europe/Madrid