version: '3'
services:
  webdav:
    build: .
    image: davidadrianrg/webdav:v1.0
    container_name: webdav
    restart: unless-stopped
    volumes:
      - /media/ssd:/share
      - ./htpasswd:/opt/nginx/conf/.htpasswd
