version: '3.3'

services:
  firefly_app:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - internal
    depends_on:
      - firefly_db

  firefly_db:
    image: mariadb
    container_name: firefly_db 
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - internal
    
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  internal: