version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - /media/ssd:/media
      - ./data/media2:/media2:ro
    environment:
      - JELLYFIN_PublishedServerUrl=${FQDN}
