version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./data/config:/config
      - /home/david/media/peliculas:/movies #optional
      - /home/david/media/series:/tv #optional
      - /home/david/media/descargas:/downloads #optional
    restart: unless-stopped