version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "LATEST" #Minecraft Game Version
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data/minecraft:/data