version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "LATEST" #Minecraft Game Version
      MEMORY: "1G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data/minecraft_data:/data
    networks:
      - minecraft_net

networks:
  minecraft_net:
    external: true