version: '3'

services:
  transmission:
    networks:
      - public
    labels:
      - caddy="${FQDN}"
      - caddy.reverse_proxy="{{upstreams 9091}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true