version: '3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    labels:
      - com.centurylinklabs.watchtower.enable="false"
      - com.centurylinklabs.watchtower.monitor-only="true"
    restart: unless-stopped