version: '3'
services:
  esphome:
    networks:
      - public
    labels:
      - caddy="${FQDN}"
      - caddy.tls="internal"
      - caddy.reverse_proxy="{{upstreams 6052}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true