version: '3'

services:
  wg-easy:
    networks:
      - public
    labels:
      - caddy="wireguard.lan"
      - caddy.tls="internal"
      - caddy.reverse_proxy="{{upstreams 51821}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true