version: '3'

services:
  wg-easy:
    networks:
      - public
    labels:
      - caddy="wireguard.${FQDN}"
      - caddy.reverse_proxy="{{upstreams 85}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true