version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wireguard
    restart: unless-stopped
    environment:
        WG_HOST: ${FQDN}
        PASSWORD: ${WG_PASSWORD}
        WG_DEFAULT_DNS: 172.18.0.20
        WG_DEFAULT_ADDRESS: 10.8.0.x
        WG_ALLOWED_IPS: 10.8.0.0/24, 172.18.0.0/24, 192.168.1.0/24
    volumes:
        - ./data/vpn/wireguard:/etc/wireguard
    ports:
        - 51820:51820/udp
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
    networks:
      public:
      private:

networks:
  private:
    external: true
  public:
    external: true
