version: '3'

services:
  dockge:
    networks:
      - public
    labels:
      - caddy="${FQDN}"
      - caddy.tls="internal"
      - caddy.reverse_proxy="{{upstreams 5001}}"
      - caddy.@denied.not.remote_ip="private_ranges"
      - caddy.abort=@denied

networks:
  public:
    external: true
